/**
 * 一份**固定的价目样例**（WP165，docs/83 §2「价目表只放云上」）。
 *
 * 官方价只在云上（`GET /v1/pricing`）；开源仓里的 demo、云端替身（`cloud-stand-in`）、
 * 合成世界与测试要一份「长得像真价目」的东西来演、来算，就用这一份——**不打网、不随云上改价而变**，
 * 所以模拟基线与测试断言稳定。
 *
 * 取的是 2026-09-27 云上那一份的快照（当时还在本仓 `packages/metering` 里，已公开过）。
 * 这不是官方价：界面上真实显示的永远是云上取到的那一份（或本机缓存的上一份）。
 * 改这一份只影响 demo / 模拟 / 测试，不改任何人的账。
 */
import type { PricingCatalog } from '@agentsws/contracts'

export const SAMPLE_PRICING_CATALOG: PricingCatalog = {
  version: 1,
  pricing: {
    version: 2,
    as_of: '2026-09-19',
    credit_cny: 1,
    ai_multiplier: 3,
    fx: {
      CNY: 1,
      USD: 7.1,
      EUR: 7.7,
    },
    entries: [
      {
        capability: 'ai.chat',
        unit: '1k_tokens',
        credits_per_unit: 0.3,
        label_zh: 'AI 对话（按 token）',
        label_en: 'AI chat (per token)',
        block: 'ai',
        models: [
          {
            model: 'deepseek-flash',
            in: 0.0064,
            out: 0.0256,
            cached: 0.0001,
            cn: true,
          },
          {
            model: 'deepseek-r1',
            in: 0.012,
            out: 0.048,
            cached: 0.012,
            cn: true,
          },
          {
            model: 'deepseek-v4-flash-0731',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'deepseek-v4-pro',
            in: 0.0281,
            out: 0.0843,
            cached: 0.0009,
            cn: true,
          },
          {
            model: 'deepseek-v4-pro',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'deepseek-v4-pro',
            in: 0.036,
            out: 0.072,
            cached: 0.036,
            cn: true,
          },
          {
            model: 'deepseek-v4-pro-0813',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'deepseek-v4.1-flash',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'deepseek-v4.1-flash',
            in: 0.006,
            out: 0.024,
            cached: 0.006,
            cn: true,
          },
          {
            model: 'glm-4.7',
            in: 0.006,
            out: 0.024,
            cached: 0.0012,
            cn: true,
          },
          {
            model: 'glm-4.7',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'glm-5',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'glm-5.2',
            in: 0.024,
            out: 0.084,
            cached: 0.006,
            cn: true,
          },
          {
            model: 'glm-5.2',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'glm-5.3',
            in: 0.024,
            out: 0.084,
            cached: 0.006,
            cn: true,
          },
          {
            model: 'glm-5.3',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'glm-5.3-flash',
            in: 0.0024,
            out: 0.0084,
            cached: 0.0007,
            cn: true,
          },
          {
            model: 'gpt-4.1',
            in: 0.0426,
            out: 0.1704,
            cached: 0.0106,
            cn: false,
          },
          {
            model: 'gpt-4.1-mini',
            in: 0.0085,
            out: 0.0341,
            cached: 0.0021,
            cn: false,
          },
          {
            model: 'gpt-4.1-nano',
            in: 0.0021,
            out: 0.0085,
            cached: 0.0005,
            cn: false,
          },
          {
            model: 'gpt-4o',
            in: 0.0533,
            out: 0.213,
            cached: 0.0266,
            cn: false,
          },
          {
            model: 'gpt-4o-mini',
            in: 0.0032,
            out: 0.0128,
            cached: 0.0016,
            cn: false,
          },
          {
            model: 'gpt-5',
            in: 0.0266,
            out: 0.213,
            cached: 0.0027,
            cn: false,
          },
          {
            model: 'gpt-5-mini',
            in: 0.0053,
            out: 0.0426,
            cached: 0.0005,
            cn: false,
          },
          {
            model: 'gpt-5-nano',
            in: 0.0011,
            out: 0.0085,
            cached: 0.0001,
            cn: false,
          },
          {
            model: 'gpt-5.4',
            in: 0.0533,
            out: 0.3195,
            cached: 0.0053,
            cn: false,
          },
          {
            model: 'gpt-5.4-mini',
            in: 0.016,
            out: 0.0958,
            cached: 0.0016,
            cn: false,
          },
          {
            model: 'gpt-5.4-nano',
            in: 0.0043,
            out: 0.0266,
            cached: 0.0004,
            cn: false,
          },
          {
            model: 'gpt-5.6-luna',
            in: 0.0043,
            out: 0.0256,
            cached: 0.0004,
            cn: false,
          },
          {
            model: 'gpt-5.6-sol',
            in: 0.0852,
            out: 0.426,
            cached: 0.0085,
            cn: false,
          },
          {
            model: 'gpt-5.6-terra',
            in: 0.0426,
            out: 0.2556,
            cached: 0.0043,
            cn: false,
          },
          {
            model: 'gpt-6-astra',
            in: 0.213,
            out: 1.065,
            cached: 0.0213,
            cn: false,
          },
          {
            model: 'kimi-k2.5',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'kimi-k2.6',
            in: 0.0195,
            out: 0.081,
            cached: 0.0033,
            cn: true,
          },
          {
            model: 'kimi-k2.7-code',
            in: 0.0195,
            out: 0.081,
            cached: 0.0039,
            cn: true,
          },
          {
            model: 'kimi-k2.7-code-highspeed',
            in: 0.039,
            out: 0.162,
            cached: 0.0078,
            cn: true,
          },
          {
            model: 'kimi-k3',
            in: 0.06,
            out: 0.3,
            cached: 0.006,
            cn: true,
          },
          {
            model: 'MiniMax-M2.5',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'qwen-max',
            in: 0.0072,
            out: 0.0288,
            cached: 0.0007,
            cn: true,
          },
          {
            model: 'qwen-plus',
            in: 0.0024,
            out: 0.006,
            cached: 0.0002,
            cn: true,
          },
          {
            model: 'qwen-turbo',
            in: 0.0009,
            out: 0.0018,
            cached: 0.0001,
            cn: true,
          },
          {
            model: 'qwen3-coder-next',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'qwen3-coder-plus',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'qwen3-max-2026-01-23',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'qwen3.5-plus',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'qwen3.6-flash',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'qwen3.6-plus',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'qwen3.7-max',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'qwen3.7-plus',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'qwen3.7-plus',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'qwen3.7-plus',
            in: 0.006,
            out: 0.024,
            cached: 0.006,
            cn: true,
          },
          {
            model: 'qwen3.8-flash',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'qwen3.8-flash',
            in: 0.0024,
            out: 0.0081,
            cached: 0.0024,
            cn: true,
          },
          {
            model: 'qwen3.8-max',
            in: 0,
            out: 0,
            cached: 0,
            cn: false,
          },
          {
            model: 'qwen3.8-max',
            in: 0.036,
            out: 0.108,
            cached: 0.0036,
            cn: true,
          },
        ],
      },
      {
        capability: 'ai.embeddings',
        unit: '1k_tokens',
        credits_per_unit: 0.0015,
        label_zh: '文本向量（按 token）',
        label_en: 'Embeddings (per token)',
        block: 'ai',
      },
      {
        capability: 'ai.image',
        unit: 'image',
        credits_per_unit: 0.5,
        label_zh: 'AI 生图（按张）',
        label_en: 'AI image generation (per image)',
        block: 'ai',
      },
      {
        capability: 'data.kol.lookup',
        unit: 'call',
        credits_per_unit: 0.2,
        label_zh: '红人库浏览 / 搜索（按次）',
        label_en: 'Creator browse / search (per call)',
        block: 'data',
      },
      {
        capability: 'data.kol.audit',
        unit: 'call',
        credits_per_unit: 3,
        label_zh: '红人体检报告（按次）',
        label_en: 'Creator audit report (per report)',
        block: 'data',
      },
      {
        capability: 'data.kol.reveal',
        unit: 'call',
        credits_per_unit: 0.8,
        label_zh: '解锁红人联系方式（按次）',
        label_en: 'Creator contact reveal (per call)',
        block: 'data',
      },
      {
        capability: 'social.fetch',
        unit: 'call',
        credits_per_unit: 0.4,
        label_zh: '社媒数据抓取（按次）',
        label_en: 'Social data fetch (per call)',
        block: 'data',
      },
      {
        capability: 'crawl.page',
        unit: 'page',
        credits_per_unit: 0.2,
        label_zh: '网页抓取（按页）',
        label_en: 'Page crawl (per page)',
        block: 'data',
      },
      {
        capability: 'transcribe.minute',
        unit: 'minute',
        credits_per_unit: 0.3,
        label_zh: '会议转写（按分钟）',
        label_en: 'Transcription (per minute)',
        block: 'data',
      },
      {
        capability: 'data.search.serp',
        unit: 'call',
        credits_per_unit: 0.2,
        label_zh: '搜索结果页（按次）',
        label_en: 'Search results page (per query)',
        block: 'data',
      },
      {
        capability: 'data.search.ai_answer',
        unit: 'call',
        credits_per_unit: 0.4,
        label_zh: 'AI 平台问答探测（每个平台一次）',
        label_en: 'AI answer probe (per platform)',
        block: 'data',
      },
      {
        capability: 'standby.seat.month',
        unit: 'seat_month',
        credits_per_unit: 99,
        label_zh: '在线值守（每座位每月）',
        label_en: 'Online standby (per seat per month)',
        block: 'data',
      },
      {
        capability: 'kol.service.monthly',
        unit: 'month',
        credits_per_unit: 30,
        label_zh: '红人营销增值服务（每月）',
        label_en: 'Influencer service (per month)',
        block: 'service',
      },
      {
        capability: 'support.service.monthly',
        unit: 'month',
        credits_per_unit: 30,
        label_zh: '客服增值服务（每月）',
        label_en: 'Customer support service (per month)',
        block: 'service',
      },
    ],
  },
  topup_tiers: {
    version: 1,
    as_of: '2026-09-19',
    credits_per_usd: 7,
    tiers: [
      {
        id: 'usd20',
        usd: 20,
        credits: 140,
        label_zh: '入门',
        label_en: 'Starter',
      },
      {
        id: 'usd50',
        usd: 50,
        credits: 350,
        label_zh: '常用',
        label_en: 'Standard',
        recommended: true,
      },
      {
        id: 'usd100',
        usd: 100,
        credits: 700,
        label_zh: '团队',
        label_en: 'Team',
      },
      {
        id: 'usd200',
        usd: 200,
        credits: 1400,
        label_zh: '年度',
        label_en: 'Annual',
      },
    ],
  },
}
